//! Skill Genesis (System 7) — Nexus замечает повторения и предлагает скиллы.
//!
//! Люди не пишут скиллы заранее — они замечают, что делают одно и то же
//! третий раз, и автоматизируют. Nexus делает то же самое с журналом полёта:
//! один и тот же `category + action` (например `memory` + `create_memory`),
//! повторённый достаточно часто, становится кандидатом в скилл.
//!
//! ```text
//! flight_records ──► detect_patterns ──► SkillProposal (proposed)
//!                                                │
//!                                     approve ───┘──► SkillRepository::upsert
//! ```
//!
//! Чистые функции здесь тестируются без БД: группировка, порог повторений,
//! генерация имени/описания. Хранение кандидатов — в `skill_proposals`
//! (миграция V25).

use serde::{Deserialize, Serialize};

use crate::core::flight::flight_recorder::{FlightCategory, FlightRecord};

/// Минимальное число повторений одного действия, чтобы оно стало кандидатом.
pub const MIN_OCCURRENCES: usize = 3;

/// Одна сигнатура повторяющегося действия: категория + действие.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
pub struct PatternSignature {
    pub category: String,
    pub action: String,
}

impl PatternSignature {
    pub fn new(category: &str, action: &str) -> Self {
        Self {
            category: category.to_string(),
            action: action.to_string(),
        }
    }
}

/// Обнаруженный паттерн: сигнатура + сколько раз и примеры.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct Pattern {
    pub signature: PatternSignature,
    pub occurrences: usize,
    /// Типы сущностей, к которым применялось действие (для описания).
    pub entity_types: Vec<String>,
    /// Примеры summaries (для читаемого описания и обучения).
    pub examples: Vec<String>,
    /// Записей всего проанализировано.
    pub scanned: usize,
}

impl Pattern {
    /// Кандидатское имя скилла: `create_memory` → `create-memory`.
    pub fn skill_name(&self) -> String {
        self.signature.action.replace('_', "-").to_lowercase()
    }

    /// Генерация описания: что делает скилл, на основе паттерна.
    pub fn description(&self) -> String {
        let mut desc = format!(
            "Automatically generated by Skill Genesis: the operation '{}' ({} category) was \
             performed {} times in the flight log.",
            self.signature.action, self.signature.category, self.occurrences,
        );
        if let Some(et) = self.entity_types.first() {
            desc.push_str(&format!(" Operates on {}.", et));
        }
        if let Some(ex) = self.examples.first() {
            desc.push_str(&format!(" Typical use: {}", truncate(ex, 160)));
        }
        desc
    }
}

/// Статус кандидата в скиллы.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum ProposalStatus {
    Proposed,
    Approved,
    Rejected,
}

impl ProposalStatus {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Proposed => "proposed",
            Self::Approved => "approved",
            Self::Rejected => "rejected",
        }
    }

    pub fn parse(s: &str) -> Self {
        match s {
            "approved" => Self::Approved,
            "rejected" => Self::Rejected,
            _ => Self::Proposed,
        }
    }
}

/// Кандидат в скиллы, сохранённый в `skill_proposals`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct SkillProposal {
    pub id: String,
    pub signature: PatternSignature,
    pub occurrences: usize,
    pub name: String,
    pub description: String,
    pub status: ProposalStatus,
    pub created_at: String,
}

/// Детекция паттернов: группировка записей по (category, action).
///
/// Чистая функция: на вход записи журнала, на выход паттерны с числом
/// повторений ≥ `min_occurrences`.
pub fn detect_patterns(records: &[FlightRecord], min_occurrences: usize) -> Vec<Pattern> {
    use std::collections::BTreeMap;

    struct Acc {
        count: usize,
        entity_types: Vec<String>,
        examples: Vec<String>,
    }

    let mut map: BTreeMap<PatternSignature, Acc> = BTreeMap::new();
    for r in records {
        let sig = PatternSignature::new(r.category.as_str(), &r.action);
        let acc = map.entry(sig).or_insert(Acc {
            count: 0,
            entity_types: Vec::new(),
            examples: Vec::new(),
        });
        acc.count += 1;
        if !r.entity_type.is_empty()
            && !acc.entity_types.contains(&r.entity_type)
            && acc.entity_types.len() < 5
        {
            acc.entity_types.push(r.entity_type.clone());
        }
        if !r.summary.is_empty() && acc.examples.len() < 3 {
            acc.examples.push(r.summary.clone());
        }
    }

    let scanned = records.len();
    let mut out: Vec<Pattern> = map
        .into_iter()
        .filter(|(_, a)| a.count >= min_occurrences)
        .map(|(signature, a)| Pattern {
            signature,
            occurrences: a.count,
            entity_types: a.entity_types,
            examples: a.examples,
            scanned,
        })
        .collect();
    out.sort_by_key(|a| std::cmp::Reverse(a.occurrences));
    out
}

/// Отфильтровать паттерны, для которых скилл уже существует или уже был
/// предложен/одобрен (чтобы не плодить дубликаты при повторном сканировании).
pub fn filter_existing(patterns: Vec<Pattern>, known: &[PatternSignature]) -> Vec<Pattern> {
    patterns
        .into_iter()
        .filter(|p| !known.contains(&p.signature))
        .collect()
}

/// Создать кандидата из паттерна.
pub fn propose(patterns: Vec<Pattern>) -> Vec<SkillProposal> {
    let now = chrono::Utc::now().to_rfc3339();
    patterns
        .into_iter()
        .map(|p| SkillProposal {
            id: crate::core::entity_id::EntityId::new().to_string(),
            signature: p.signature.clone(),
            occurrences: p.occurrences,
            name: p.skill_name(),
            description: p.description(),
            status: ProposalStatus::Proposed,
            created_at: now.clone(),
        })
        .collect()
}

fn truncate(s: &str, max: usize) -> String {
    if s.len() <= max {
        s.to_string()
    } else {
        let mut end = max;
        while end > 0 && !s.is_char_boundary(end) {
            end -= 1;
        }
        format!("{}…", &s[..end])
    }
}

/// Человекочитаемый список кандидатов.
pub fn render_proposals(proposals: &[SkillProposal]) -> String {
    if proposals.is_empty() {
        return "No skill proposals yet — run a scan first.".to_string();
    }
    let mut out = String::with_capacity(512);
    for p in proposals {
        out.push_str(&format!(
            "  [{}] {} ({} × {}) — {}\n",
            p.status.as_str(),
            p.name,
            p.occurrences,
            p.signature.category,
            truncate(&p.description, 120),
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn record(
        category: FlightCategory,
        action: &str,
        entity_type: &str,
        summary: &str,
    ) -> FlightRecord {
        FlightRecord::success(
            None,
            "agent",
            category,
            action,
            entity_type,
            "id-1",
            summary,
            serde_json::json!({}),
            5,
        )
    }

    /// N одинаковых записей (FlightRecord не Copy, поэтому не `[r; N]`).
    fn n_records(
        n: usize,
        category: FlightCategory,
        action: &str,
        entity_type: &str,
        summary: &str,
    ) -> Vec<FlightRecord> {
        std::iter::repeat_with(|| record(category, action, entity_type, summary))
            .take(n)
            .collect()
    }

    #[test]
    fn detects_repeated_pattern() {
        let mut records = Vec::new();
        for i in 0..5 {
            let mut r = record(
                FlightCategory::Memory,
                "create_memory",
                "MemoryRecord",
                "Created memory",
            );
            r.entity_id = format!("id-{i}");
            records.push(r);
        }
        records.push(record(
            FlightCategory::Conflict,
            "resolve_conflict",
            "ConflictGroup",
            "Resolved",
        ));
        let patterns = detect_patterns(&records, MIN_OCCURRENCES);
        assert_eq!(patterns.len(), 1);
        assert_eq!(patterns[0].signature.action, "create_memory");
        assert_eq!(patterns[0].occurrences, 5);
        assert_eq!(patterns[0].scanned, 6);
    }

    #[test]
    fn below_threshold_is_ignored() {
        let records = vec![
            record(FlightCategory::Memory, "create_memory", "MemoryRecord", "a"),
            record(FlightCategory::Memory, "create_memory", "MemoryRecord", "b"),
        ];
        assert!(detect_patterns(&records, 3).is_empty());
        assert_eq!(detect_patterns(&records, 2).len(), 1);
    }

    #[test]
    fn sorts_by_occurrences_desc() {
        let mut records = vec![
            record(FlightCategory::Memory, "rare", "MemoryRecord", "a"),
            record(FlightCategory::Memory, "rare", "MemoryRecord", "b"),
        ];
        for _ in 0..4 {
            records.push(record(
                FlightCategory::Firewall,
                "quarantine",
                "MemoryRecord",
                "q",
            ));
        }
        let patterns = detect_patterns(&records, 2);
        assert_eq!(patterns.len(), 2);
        assert_eq!(patterns[0].signature.action, "quarantine");
    }

    #[test]
    fn skill_name_is_kebab_case() {
        let p = detect_patterns(
            &n_records(
                3,
                FlightCategory::Memory,
                "create_memory",
                "MemoryRecord",
                "a",
            ),
            3,
        )
        .remove(0);
        assert_eq!(p.skill_name(), "create-memory");
        assert!(p.description().contains("3 times"));
        assert!(p.description().contains("MemoryRecord"));
    }

    #[test]
    fn filter_existing_drops_known() {
        let patterns = detect_patterns(
            &n_records(
                3,
                FlightCategory::Memory,
                "create_memory",
                "MemoryRecord",
                "a",
            ),
            3,
        );
        let known = vec![patterns[0].signature.clone()];
        assert!(filter_existing(patterns.clone(), &known).is_empty());
        assert_eq!(filter_existing(patterns, &[]).len(), 1);
    }

    #[test]
    fn propose_builds_proposals() {
        let patterns = detect_patterns(
            &n_records(
                4,
                FlightCategory::Memory,
                "create_memory",
                "MemoryRecord",
                "a",
            ),
            3,
        );
        let proposals = propose(patterns);
        assert_eq!(proposals.len(), 1);
        assert_eq!(proposals[0].name, "create-memory");
        assert_eq!(proposals[0].status, ProposalStatus::Proposed);
        assert!(!proposals[0].id.is_empty());
        assert!(!proposals[0].created_at.is_empty());
    }

    #[test]
    fn render_lists_proposals() {
        let patterns = detect_patterns(
            &n_records(
                3,
                FlightCategory::Memory,
                "create_memory",
                "MemoryRecord",
                "a",
            ),
            3,
        );
        let proposals = propose(patterns);
        let text = render_proposals(&proposals);
        assert!(text.contains("create-memory"));
        assert!(text.contains("proposed"));
        assert!(render_proposals(&[]).contains("No skill proposals"));
    }

    #[test]
    fn dedupes_entity_types() {
        let mut records = Vec::new();
        for et in ["MemoryRecord", "MemoryRecord", "Entity", "Entity"] {
            records.push(record(FlightCategory::Memory, "create_memory", et, "a"));
        }
        let patterns = detect_patterns(&records, 3);
        assert_eq!(patterns[0].entity_types, vec!["MemoryRecord", "Entity"]);
    }
}
